config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, skip: :registrations,
                       path_names: { sign_in: "signin", sign_out: "signout" }

    devise_scope :user do
      scope :join do
        get :host, to: "users#new",
                   as: :host_registration,
                   defaults: { type: "host" }

        get :volunteer, to: "users#new",
                        as: :volunteer_registration,
                        defaults: { type: "volunteer" }

        post "" => "users#create", as: :user_registration
      end

      scope :account do
        get :cancel, to: "users#cancel", as: :cancel_user_registration

        get :edit, to: "users#edit", as: :edit_user_registration
        patch :update, to: "users#update", as: :update_user_registration

        get :delete, to: "users#delete", as: :confirm_delete_account
        delete :destroy, to: "users#destroy", as: :delete_account
      end
    end

    resources :countries, only: [] do
      resources :regions, only: :index
    end

    resources :donations, only: %i[new create show]

    resources :users, only: %i[index show], constraints: { id: /\d+/ } do
      resources :pictures
      resources :feedbacks, except: :show
    end

    resources :conversations, except: %i[new create]

    get "help" => "static_pages#help"
    get "about" => "static_pages#about"
    get "contact" => "static_pages#contact"
    get "terms" => "static_pages#terms"
    get "robots.txt" => "static_pages#robots"

    root "static_pages#home"
  end

  ActiveAdmin.routes(self)
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

#
# Controller for static pages
#
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def donate
  end

  def terms
  end

  def robots
    robots = File.read(Rails.root + "config/robots.#{Rails.env}.txt")
    render plain: robots, layout: false
  end
end

app/views/static_pages/_donation_thumbnail.html.slim
= link_to new_donation_path do
  .home-thumbnail
    = image_tag "contribute.png", alt: "contribute"
    h3= t("static_pages.home.contribute")

    p= t("static_pages.home.contribute_desc")

app/views/static_pages/about.html.slim
- provide :title, t(".title")

.main-padded
  header
    h1= t(".title")

  p= t(".description")

app/views/static_pages/contact.html.slim
- provide :title, t(".title")

.main-padded
  header
    h1= t(".title")

  p= t(".description_html", mail: mail_to("nipanipa@riseup.net"))

app/views/static_pages/help.html.slim
- provide :title, t(".title")

.main-padded
  header
    h1= t(".title")

  p NiPaNiPa is a common place where travelers willing to help (and save some
    money) and hosts in need of help can get in touch. Getting started is very
    simple.

  h4 I'm a host

  h5 Get Started
  ol
    li Sign-up and fill up your profile describing your project
    li Reply to interested volunteers or contact them yourself
    li Host helpers
    li After the experience, you can rate your helpers
    li You can also help us stay alive by making a donation

  h5 Advice
  ol
    li Please give as much detail as possible about your project on your profile
       so that volunteers have a clear idea of what to expect

    li Specify any "house rules" (no meat, no alcohol, no smoking) beforehand so
       that volunteers are well aware of them

    li Helpers are not volunteers per se, they are closer than workers because
       they received accommodation & food in exchange for their work. Don't
       treat them like cheap/free labor force. We consider 20h a week to be a
       reasonable amount of work time in exchange for food and accommodation.
       However, that depends solely upon the agreement you reach with your
       helper.

    li Treat helpers like family: help them get to know the local culture, give
       them tips and help them every way you can

    li Don't charge helpers

    li Rate your helpers and donate something to NiPaNiPa if the experience was
       satisfactory. Both actions will rise your karma and that will help you
       find better helpers

  h4 I'm a traveler

  h5 Get Started
  ol
    li Sign-up and fill up your profile describing yourself and your skills
    li Search for hosts and contact them
    li Go live and work by your host
    li After the experience, you can rate your host
    li You can also help us stay alive by making a donation

  h5 Advice
  ol
    li In most cases, hosts will provide accommodation and food in exchange for
       a set amount of hours of work a week, but make sure that's stated
       clearly before leaving.

    li Ask the host ANY questions that come to your mind before leaving so you
       can both match your expetatios beforehand.

    li Try to contect at least 1 month in advance, specially if it's a remote
       place where internet access might be limited.

    li Keep a positive attitude. Sometimes the accommodation, food or life style
       won't be as good as it is in your home country, but that's part of the
       experience: living like a local.

    li NiPaNiPa charges nothing and barely survive. For now, it just provide a
       meeting point but it cannot arrange transport or visas.

    li Please, take 5 minutes to rate your experience after it takes place.
       Also, consider contributing a few bucks to NiPaNiPa if you enjoyed your
       experience and want us to stay alive. Both of this actions will rise
       your karma and that will help you find better hosts.

  = image_tag "help.png", alt: "help"

app/views/static_pages/home.html.slim
.home-explore
  = link_to users_path, class: "thmb-lnk" do
    .explore-thumbnail
      h1= t("static_pages.home.explore")

      p= t("static_pages.home.explore_desc")

  .pictures-thumbnail.carousel.slide data-ride="carousel" data-interval="4000"
    .carousel-inner
      - Picture.random(8).each_with_index do |picture, i|
        .item class=("active" if i.zero?)
          = link_to image_tag(picture.image.url(:large), alt: picture.name),
                    picture.user
          .carousel-caption
            h3= picture.name

    = link_to ".pictures-thumbnail", class: "left carousel-control",
                                     role: "button",
                                     "data-slide" => "prev" do
      span.glyphicon.glyphicon-chevron-left

    = link_to ".pictures-thumbnail", class: "right carousel-control",
                                     role: "button",
                                     "data-slide" => "next" do
      span.glyphicon.glyphicon-chevron-right

.home-signup
  = link_to host_registration_path, class: "thmb-lnk" do
    .host-thumbnail
      = image_tag "host.png", alt: "signup host"
      h1= t("static_pages.home.host")

      p= t("static_pages.home.host_desc")

  = link_to volunteer_registration_path, class: "thmb-lnk" do
    .volunteer-thumbnail
      = image_tag "volunteer.png", alt: "signup volunteer"
      h1= t("static_pages.home.volunteer")

      p= t("static_pages.home.volunteer_desc")

app/views/static_pages/terms.html.slim
- provide :title, t(".title")

.main-padded
  header
    h1 Terms and Conditions

  p By registering and using this site you acknowledge that you have read,
    understand and agree to the following terms and conditions

  ol
    li
      h5 Registration.
      p By registering with NiPaNiPa and creating your profile, you agree to
        provide accurate, up-to-date and complete information about yourself.
        You further agree to try to keep this information accurate and up to
        date at all times, specially regarding your email address, since that
        is the primary means of communication with you about your account. User
        profile's are submitted and updated by or with the permission of users.
        Every effort has been made by NiPaNiPa to provide accurate and honest
        information. As part of the registration process, you will designate a
        password, subject to our password security requirements. It is your
        responsibility to keep this password confidential. If you find out that
        your password or account is being used by someone without your consent,
        or you discover any other breach of security, you agree to notify us
        promptly without delay.

    li
      h5 Privacy
      p We are committed to safeguarding your privacy. However, by submitting
        photographs of yourself and any other personal information, you allow
        any member of NiPaNiPa to view and use this information. Under normal
        circumstances we will not transfer your personal information to
        unaffiliated third parties without your consent. However, we reserve
        the right to transfer such information without your consent in the
        following cases: to prevent an emergency, to protect or enforce our
        legal rights, to protect or enforce legal rights of a third party or in
        pursuance to a court order or subpoena or as otherwise required or
        permitted by law. This also applies to messages you send through
        NiPaNiPa. While these messages are normally only read by respective
        senders and recipients, you agree to disclose those messages to
        NiPaNiPa volunteers for spam monitoring. Should our filters detect
        misuse of the site that is not in accordance with our terms and
        conditions we reserve the right to intervene and take reasonable
        appropriate action. NiPaNiPa may use the email address you provided
        upon registration in order to send you regular newsletters, which,
        however, you can unsubscribe from. In addition, NiPaNiPa reserves the
        right to edit any listing and post a stock photo of the area in no
        photo has been uploaded in the profile. The software running this
        website is licensed under the MIT License.

    li
      h5 Liability
      p We offer a platform for registered members to arrange volunteer work
        and accommodation exchange. Although every effort has been made to
        ensure the correctness of this information, NiPaNiPa hereby disclaims
        any liability for any loss or damage caused by errors, omissions,
        misleading information, or any potential problem caused by information
        provided via nipanipa.com. We do not warrant to offer an error-free,
        nor uninterrupted nor fast service. We shall not be responsible or
        liable in case of a dispute with one of our members. You thus exempt us
        herewith from any claims or liabilities whatsoever arising from or in
        connection with our service. NiPaNiPa reserves the right to modify,
        suspend or discontinue the service, in its sole discretion, at any time
        and without notice. You agree that NiPaNiPa is not and will not be
        liable to you for any modification, suspension or discontinuance of the
        service. It should be remembered that NiPaNiPa only provides the
        contact information to enable educational and cultural exchange rather
        like a classified listing and is NOT a travel agency or organised
        exchange program. All arrrangements are entirely between the host and
        the volunteer. If this terms and conditions are not met and you don't
        use the site with the spirit it was created, NiPaNiPa reserves the
        right to edit, close and/or delete your account and profile and thereby
        remove any information and prevent you from using the site. We also
        reserve the right to remove user accounts if, in our sole opinion,
        hospitality or help offered by hosts or volunteers is abused. NiPaNiPa
        accepts no liability or will be held responsible in any way for work or
        host related incidents under any circumstances. We highly recommend
        that all volunteers take out an adequate insurance policy and that all
        hosts also hold insurance to cover any work related incident. We also
        recommend all volunteers to obtain the relevant visa for the country
        they are travelling to and submit any questions regarding travel and
        visas to the relevent embassy in their home country before travelling.

    li
      h5 General Conduct

      p You agree that you shall not
      ol
        li Interfere with or disrupt (or attempt to interfere with or disrupt)
           this service or servers, through, including, but not limited to, the
           use of viruses, cancel bots, Trojan horses, harmful code, flood
           pings, denial-of-service attacks, packet or IP spoofing, forged
           routing or electronic mail address information or similar methods or
           technologies.

        li Provide any information to NiPaNiPa that is false or misleading,
           that would otherwise hide your identity or that you do not have the
           right to disclose.

        li Violate any applicable law or regulation. Spanish law is applicable
           here.

        li Violate the rights of any third party, including, but not limited
           to, intellectual property, privacy, publicity or contractual rights.

        li Collect, store or abuse any information you obtain through our
           service including any information about any other user for any
           unauthorized purposes.

        li Use our services to transmit, distribute, post or submit any
           information concerning any other person or entity, including, but
           not limited to, personal contact information or credit, debit,
           calling card or account numbers.

        li Molest, "stalk" or harass any other user of our services.

        li Use our services for any commercial purpose especially in connection
           with the distribution of unsolicited commercial email ("Spam") or
           advertisements.

        li Assist any third party in doing any of the foregoing.

      p You agree to defend, indemnify, and hold harmless NiPaNiPa and its
        volunteers, from and against any claims, liabilities, damages, losses,
        and expenses, including, but not limited to, reasonable legal and
        expert fees, arising out of or in any way connected with your access to
        or use of the services, or your violation of these terms.

    li
      h5 Content
      p You are responsible for all the content you upload, download, and
        otherwise copy, distribute and display using the service. You must
        have the legal right to copy, distribute and display all parts of any
        content that you upload, download and otherwise copy, distribute and
        display. Content provided to you by others, or made available through
        websites, magazines, books and other sources, may be protected by
        copyright and should not be uploaded, downloaded, or otherwise
        copied, distributed or displayed without the consent of the copyright
        owner or as otherwise permitted by law.

      p You agree that you shall not post or submit any content that

      ol
        li Is libelous.

        li Contains nudity, pornography, pedophile or sexually explicit
           content.

        li Is in any way discriminating against ethnic, racial, sexual or
           religious groups by stereotypical depiction or otherwise.

        li Contains offensive language or images.

        li Glorifies violence and the use of drugs or characterize either as
           acceptable or desirable.