config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, skip: :registrations,
                       path_names: { sign_in: "signin", sign_out: "signout" }

    devise_scope :user do
      scope :join do
        get :host, to: "users#new",
                   as: :host_registration,
                   defaults: { type: "host" }

        get :volunteer, to: "users#new",
                        as: :volunteer_registration,
                        defaults: { type: "volunteer" }

        post "" => "users#create", as: :user_registration
      end

      scope :account do
        get :cancel, to: "users#cancel", as: :cancel_user_registration

        get :edit, to: "users#edit", as: :edit_user_registration
        patch :update, to: "users#update", as: :update_user_registration

        get :delete, to: "users#delete", as: :confirm_delete_account
        delete :destroy, to: "users#destroy", as: :delete_account
      end
    end

    resources :countries, only: [] do
      resources :regions, only: :index
    end

    resources :donations, only: %i[new create show]

    resources :users, only: %i[index show], constraints: { id: /\d+/ } do
      resources :pictures
      resources :feedbacks, except: :show
    end

    resources :conversations, except: %i[new create]

    get "help" => "static_pages#help"
    get "about" => "static_pages#about"
    get "contact" => "static_pages#contact"
    get "terms" => "static_pages#terms"
    get "robots.txt" => "static_pages#robots"

    root "static_pages#home"
  end

  ActiveAdmin.routes(self)
end

app/models/user.rb
# frozen_string_literal: true

#
# Main class implementing both Host and Volunteer through STI
#
class User < ApplicationRecord
  devise :confirmable, :database_authenticatable, :recoverable, :registerable,
         :rememberable, :trackable, :validatable

  validates :description, length: { maximum: 2500 }
  validates :name, presence: true, length: { maximum: 38 }

  before_destroy -> { Message.sent_or_received_by(id).destroy_all }

  has_many :donations, dependent: :nullify

  has_many :sectorizations, dependent: :destroy
  has_many :work_types, through: :sectorizations, inverse_of: :users

  has_many :language_skills, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :language_skills
  has_many :languages, through: :language_skills, inverse_of: :users

  has_many :pictures, dependent: :destroy

  belongs_to :region

  delegate :country, :country_id, to: :region
  scope :from_country, ->(country_id) do
    where(regions: { country_id: country_id })
  end

  delegate :continent, :continent_id, to: :country
  scope :from_continent, ->(continent_id) do
    where(countries: { continent_id: continent_id })
  end

  scope :by_latest_sign_in, -> { order("last_sign_in_at DESC NULLS LAST") }

  scope :confirmed, -> { where.not(confirmed_at: nil) }

  default_scope { includes(region: :country) }

  def blank_img_and_cache(att)
    att["image"].blank? && att["image_cache"].blank?
  end

  accepts_nested_attributes_for :pictures,
                                reject_if: ->(att) { blank_img_and_cache(att) }

  has_many :sent_feedbacks,
           -> { order(updated_at: :desc).includes(:recipient) },
           class_name: "Feedback",
           foreign_key: "sender_id",
           dependent: :destroy,
           inverse_of: :sender

  has_many :received_feedbacks,
           -> { order(updated_at: :desc).includes(:sender) },
           class_name: "Feedback",
           foreign_key: "recipient_id",
           dependent: :destroy,
           inverse_of: :recipient

  def messages_with(uid)
    Message.between(id, uid).non_deleted_by(id)
  end

  scope :currently_available, -> { available_in?(Time.zone.now.mon) }
  scope :available_in?, ->(m) { where("availability_mask & ? > 0", 2**(m - 1)) }

  def availability=(availability)
    self.availability_mask = ArrayMask.new((1..12).to_a).mask(availability)
  end

  def availability
    ArrayMask.new((1..12).to_a).unmask(availability_mask)
  end

  def available_in?(month)
    availability.include?(month)
  end

  def location
    "#{region.name}, #{region.country.name}"
  end

  # Use a single route for all subclasess
  def self.model_name
    ActiveModel::Naming.instance_method(:model_name).bind(User).call
  end

  # Use a single partial path for all subclasses
  def to_partial_path
    "users/user"
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

#
# Main controller for all users (hosts and volunteers)
#
class UsersController < Devise::RegistrationsController
  before_action :authenticate_user!, only: %i[edit update delete]

  def new
    super do |resource|
      resource.region = Country.default.regions.default

      language = Language.find_by(code: I18n.locale)
      break unless language

      resource.language_skills.build(language: language, level: :expert)
    end
  end

  def index
    @users = apply_filters.by_latest_sign_in.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @feedback_pairs = Feedback.pairs(@user)
  end

  def edit
    @user = current_user
  end

  def update
    super
  end

  def delete
  end

  private

  def apply_filters
    users = filter_class.confirmed
    users = users.currently_available if params[:availability].nil?
    users = users.from_continent(continent_id.to_i) if continent_id
    users = users.from_country(country_id.to_i) if country_id
    users
  end

  def country_id
    params[:cou_id]
  end

  def continent_id
    params[:con_id]
  end

  #
  # Override devise redirections
  #
  def after_update_path_for(resource)
    resource
  end

  def after_inactive_sign_up_path_for(_resource)
    new_user_session_path
  end

  def after_sign_out_path_for(_resource)
    users_path
  end

  #
  # Override devise default of asking password for updates
  #
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def proper_fields
    %i[description email name password password_confirmation region_id skills]
  end

  def nested_fields
    [
      availability: [],
      work_type_ids: [],
      language_skills_attributes: %i[id language_id level _destroy]
    ]
  end

  def user_fields
    proper_fields + nested_fields
  end

  def host_params
    [:accommodation, *user_fields]
  end

  def volunteer_params
    user_fields
  end

  #
  # Correctly resolve actual class from params
  #
  def resource_class
    params[:type] ? detected_class_from(params[:type]) : User
  end

  def resource_class_from_params
    params[:type] ? detected_class_from(params[:type]) : nil
  end

  def resource_class_from_current_user
    return User unless current_user

    current_user.is_a?(Host) ? Volunteer : Host
  end

  def filter_class
    resource_class_from_params || resource_class_from_current_user
  end
  helper_method :filter_class

  #
  # Use a single devise mapping for both classes
  #
  def devise_mapping
    Devise.mappings[:user]
  end

  def detected_class_from(type)
    [Volunteer, Host, User].find { |klass| klass.name == type.classify }
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

#
# Various utilites for user pages
#
module UsersHelper
  def avatar_for(user, options = { style: :small })
    range = karma_to_type(user.karma)
    url = "#{user.type.underscore}#{range}_#{options[:style]}.png"
    alt = "#{user.type} avatar"
    image_tag(url, alt: alt)
  end

  def avatar_link_for(user, options = { style: :small })
    link_to avatar_for(user, options), user
  end

  def badge_content(name, value)
    badge = t("shared.badge.#{name}")
    key = content_tag(:strong, "#{badge}:")

    content_tag(:span, safe_join([key, value || unknown], " "))
  end

  def karma_to_type(karma)
    return 1 if karma.negative?
    return 2 if karma.zero?
    return 3 if karma == 1
    return 4 if karma >= 2 && karma < 10
    5
  end

  def unknown
    content_tag(:em, t("shared.unknown"))
  end
end

app/views/users/_calendar.html.slim
table.calendar
  tr
    - 12.times do |i|
      th= t("date.abbr_month_names")[i + 1]
  tr
    - 12.times do |i|
      td
        - if user.available_in?(i + 1)
          | ✔
        - else
          | ✘

app/views/users/_filters.html.slim
ul.nav.nav-pills.nav-stacked
  li.nav-header= t(".availability")

  li id="now" class=("active" if params[:availability].nil?)
    = link_to t(".now"), users_path(filter_params.except(:availability))

  li id="whenever" class=("active" if params[:availability] == "any")
    = link_to t(".whenever"),
              users_path(filter_params.merge(availability: "any"))

  li.nav-header= t(".people")

  - %w[user host volunteer].each do |type|
    li id=type class=("active" if filter_class.name.downcase == type)
      = link_to t(".#{type}"), users_path(filter_params.merge(type: type))

  li.nav-header= t(".places")

  li.continent class=("active" unless params[:con_id] || params[:cou_id])
    = link_to t(".wherever"), users_path(filter_params.except(:con_id, :cou_id))

  - Continent.find_each do |con|
    = render "continents/show", con: con

app/views/users/_form.html.slim
= simple_form_for resource, url: url, html: { class: "form-vertical user-form",
                                              multipart: true,
                                              role: "form" },
                                      defaults: { wrapper: :full_width } do |f|

  = hidden_field_tag :type, resource.type

  .form-row
    = f.input :name, wrapper: :half_width
    = f.input :email, wrapper: :half_width

  - if resource.new_record?
    .form-row
      = f.input :password, hint: resource.errors.empty?, wrapper: :half_width
      = f.input :password_confirmation, wrapper: :half_width

  .form-row
    = render "location", f: f

  .form-row
    = f.input :description, label: t(".description_#{resource.type.underscore}")

  .form-row
    = f.input :availability,
        as: :check_boxes,
        wrapper: :vertical_radio_and_checkboxes,
        wrapper_html: { class: "user-availability" },
        item_wrapper_class: "calendar",
        collection: (1..12).to_a,
        checked: resource.availability,
        label_method: ->(m) { t("date.abbr_month_names")[m] },
        value_method: :to_s

  .form-row
    = render "language_skills", f: f

  .form-row
    = render "work_types", f: f, user: resource

  .form-row
    = f.input :skills, label: t(".skills_#{resource.type.underscore}")

  .form-row
    = f.input :accommodation if resource.type == "Host"

  .form-group
    = f.button :submit, class: "primary-buttom pull-right"

app/views/users/_language_skill_fields.html.slim
.nested-fields
  = f.input :id, as: :hidden

  .language-select
    = f.collection_select :language_id,
                          Language.all,
                          :id,
                          :to_s,
                          include_blank: t(".language")

  .language-select
    = f.select :level, LanguageSkill.level.options, include_blank: t(".level")

  .language-link
    = link_to_remove_association t(".remove_language"), f

app/views/users/_language_skills.html.slim
.form-group.col-md-12
  label.control-label
    = t(".title")
  .controls
    #language_skills
      = f.simple_fields_for :language_skills, wrapper: false do |builder|
        = render "language_skill_fields", f: builder

    #language-add.links.add-language-button
      = link_to_add_association t(".add_language"), f, :language_skills

app/views/users/_location.html.slim
= f.input :country_id,
    collection: Country.options,
    input_html: { \
      data: { \
        "regions-url" => country_regions_path(":country_id") \
      } \
    },
    include_blank: false,
    wrapper: :half_width

= f.input :region_id,
    collection: f.object.country.regions,
    selected: f.object.region.id,
    include_blank: false,
    wrapper: :half_width

app/views/users/_pictures.html.slim
= render "shared/empty", message: "nopictures" if pictures.empty?

- pictures.each do |p|
  = link_to user_pictures_path(p.user, anchor: "image-#{p.id}") do
    - image_tag p.image.url(:small)

app/views/users/_user.html.slim
li
  = link_to user do
    .user-thumbnail
      .user-thumbnail-badges
        = avatar_for user
        .karma
          = t(".karma").titleize
          span
            strong= user.karma

      .user-thumbnail-data
        h5= user.name

        / TODO: Make the "currently logged in" feature work. devise's
        / `current_sign_in_at` (trackable) does not seem to work as I
        / expected. It could be fixed (i think) by adding a Warden's
        / before_logout hook
        .user-thumbnail-login.col-md-6.col-sm-12
          | #{t(".last_login")}: #{user.last_sign_in_at}

        .user-thumbnail-location.col-md-6.col-sm-12
          | #{t(".location")}: #{user.location}

        .user-thumbnail-shortdesc
          = truncate user.description,
              length: 400,
              separator: " ",
              omission: "..."

app/views/users/_work_types.html.slim
.form-group.col-md-12
  label.control-label
    = t(".title_#{user.type.underscore}")

  .work-type-list
    - 3.times do |i|
      .checkbox-list
        = f.collection_check_boxes :work_type_ids,
                                   WorkType.limit(5).offset(5 * i).to_a,
                                   :id,
                                   :name,
                                   item_wrapper_class: "checkbox" do |b|
          = b.check_box + t("work_types.#{b.text}")

app/views/users/delete.html.slim
- provide :title, t(".title")

.main-padded
  header
    h1= t(".title")
    h2= t(".subtitle")

  = simple_form_for current_user, url: :delete_account, method: :delete do |f|
    = f.button :submit, t(".title"), class: "primary-buttom btn-danger"

app/views/users/edit.html.slim
- provide :title, t(".title")

.main-padded
  header
    h1= t(".header")

  = render "form", url: update_user_registration_path

app/views/users/index.html.slim
= provide :title, t(".title")

.main-unpadded
  aside.sidebar-users
    = render "filters"

  .list-users
    ul.user-thumbnails
      - @users.each do |user|
        = render partial: "user",
                 object: ProfileSummaryPresenter.new(user, self)

    = paginate @users

app/views/users/new.html.slim
- provide :title, t(".title")

.main-padded
  header
    h1= t(".header_#{resource.type.underscore}")

  = render "form", url: user_registration_path

app/views/users/show.html.slim
- provide :title, @user.name

= render layout: "shared/profile", locals: { user: @user } do
  .col-md-6
    .box
      h3= t("users.show.description")

      p= simple_format(Rinku.auto_link(@user.description))

    .box
      h3= t("users.show.skills_#{@user.type.underscore}")

      p= simple_format(@user.skills)

  .col-md-6
    .box
      h3= t("users.show.availability")

      = render "calendar", user: @user

    - if @user.type == "Host"
      .box
        h3= t("users.show.accommodation")

        p= simple_format(@user.accommodation)

    .box
      h3= link_to t("users.show.pictures"), user_pictures_path(@user)

      = render "pictures", pictures: @user.pictures

    .box
      h3= link_to feedback_count(@feedback_pairs), user_feedbacks_path(@user)

      = render partial: "feedbacks/feedbacks", object: @feedback_pairs