config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, skip: :registrations,
                       path_names: { sign_in: "signin", sign_out: "signout" }

    devise_scope :user do
      scope :join do
        get :host, to: "users#new",
                   as: :host_registration,
                   defaults: { type: "host" }

        get :volunteer, to: "users#new",
                        as: :volunteer_registration,
                        defaults: { type: "volunteer" }

        post "" => "users#create", as: :user_registration
      end

      scope :account do
        get :cancel, to: "users#cancel", as: :cancel_user_registration

        get :edit, to: "users#edit", as: :edit_user_registration
        patch :update, to: "users#update", as: :update_user_registration

        get :delete, to: "users#delete", as: :confirm_delete_account
        delete :destroy, to: "users#destroy", as: :delete_account
      end
    end

    resources :countries, only: [] do
      resources :regions, only: :index
    end

    resources :donations, only: %i[new create show]

    resources :users, only: %i[index show], constraints: { id: /\d+/ } do
      resources :pictures
      resources :feedbacks, except: :show
    end

    resources :conversations, except: %i[new create]

    get "help" => "static_pages#help"
    get "about" => "static_pages#about"
    get "contact" => "static_pages#contact"
    get "terms" => "static_pages#terms"
    get "robots.txt" => "static_pages#robots"

    root "static_pages#home"
  end

  ActiveAdmin.routes(self)
end

app/views/shared/_badge.html.slim
.quickinfo id="#{name}info"
  .icon-info
    = image_tag "#{name}.png"

  .content-info
    = badge_content(name, content)

app/views/shared/_empty.html.slim
.no-elements
  em= t("shared.#{message}")

app/views/shared/_profile.html.slim
div class="profile-header-#{user.type.underscore}"
  = render "shared/profile_header", user: present(user)

.profile-content
  = yield

app/views/shared/_profile_header.html.slim
.user-picture
  = avatar_link_for user, style: :medium

.user-info
  .user-name
    h3
      strong= user.name

  .user-icons
    .user-status
      = render "shared/badge", name: "karma", content: user.karma
      = render "shared/badge", name: "location", content: user.location

      = render "shared/badge", name: "last_login",
                               content: user.current_sign_in_at

      = render "shared/badge", name: "member_since", content: user.created_at

    .user-knowledge
      = render "shared/badge", name: "categories", content: user.categories

      = render "shared/badge", name: "languages", content: user.languages

  .no-gutter-row
    .col-md-6.col-sm-9.col-xs-9
      ul.nav.nav-tabs
        - user.tabs.each do |options|
          li class=active_if_same_canonical(options[:path])
            = link_to(options[:name], options[:path])

    .col-md-6.col-sm-3.col-xs-3
      ul.action-group.btn-group role="group"
        - user.actions.each do |link|
          li.btn.btn-default
            = link_to(link[:dest]) do
              .icon-info.glyphicon class="glyphicon-#{link[:class]}"
              .content-info= link[:name]

app/views/shared/_signin.html.slim
= simple_form_for User.new,
                  url: user_session_path,
                  wrapper: :inline_form,
                  wrapper_mappings: { boolean: :vertical_boolean } do |f|
  = f.input :email, autofocus: true

  = f.input :password

  = f.input :remember_me, as: :boolean, inline_label: t("sessions.remember_me")

  = f.button :submit, t("sessions.signin"), class: "signin-button"

.forgot-your-pwd
  = link_to t("sessions.forgot_your_pwd?"), new_password_path(:user)