config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, skip: :registrations,
                       path_names: { sign_in: "signin", sign_out: "signout" }

    devise_scope :user do
      scope :join do
        get :host, to: "users#new",
                   as: :host_registration,
                   defaults: { type: "host" }

        get :volunteer, to: "users#new",
                        as: :volunteer_registration,
                        defaults: { type: "volunteer" }

        post "" => "users#create", as: :user_registration
      end

      scope :account do
        get :cancel, to: "users#cancel", as: :cancel_user_registration

        get :edit, to: "users#edit", as: :edit_user_registration
        patch :update, to: "users#update", as: :update_user_registration

        get :delete, to: "users#delete", as: :confirm_delete_account
        delete :destroy, to: "users#destroy", as: :delete_account
      end
    end

    resources :countries, only: [] do
      resources :regions, only: :index
    end

    resources :donations, only: %i[new create show]

    resources :users, only: %i[index show], constraints: { id: /\d+/ } do
      resources :pictures
      resources :feedbacks, except: :show
    end

    resources :conversations, except: %i[new create]

    get "help" => "static_pages#help"
    get "about" => "static_pages#about"
    get "contact" => "static_pages#contact"
    get "terms" => "static_pages#terms"
    get "robots.txt" => "static_pages#robots"

    root "static_pages#home"
  end

  ActiveAdmin.routes(self)
end

app/views/layouts/_analytics.html.slim
javascript:
  var _paq = _paq || [];
  _paq.push(["trackPageView"]);
  _paq.push(["enableLinkTracking"]);

  (function () {
    var u = "https://nipatras.xyz/";
    _paq.push(["setTrackerUrl", u + "piwik.php"]);
    _paq.push(["setSiteId", 1]);

    var d = document;
    var g = d.createElement("script");
    var s = d.getElementsByTagName("script")[0];

    g.type = "text/javascript";
    g.async = true;
    g.defer = true;
    g.src = u + "piwik.js";
    s.parentNode.insertBefore(g, s);
  })();

noscript
  p
    img[
      src="https://nipatras.xyz/piwik.php?idsite=1&rec=1"
      style="border:0;"
      alt=""
    ]

app/views/layouts/_footer.html.slim
footer
  .wrapper
    nav.footer-links
      ul
        li
          small
            - trastevere_site = "http://trasteverestudio.com"
            | (c) 2014 NiPaNiPa by #{link_to "Trastévere", trastevere_site}

        li= link_to t("static_pages.terms.title"), terms_path

        li= link_to t("static_pages.about.title"), about_path

        li= link_to t("static_pages.contact.title"), contact_path

    nav.social-links
      ul
        li
          - fb_url = "https://www.facebook.com/pages/Nipa-Nipa/282213028588722"
          - link_to fb_url do
            = image_tag "facebook.png", alt: "Facebook"

        li
          = link_to "https://twitter.com/nipanipaproject" do
            = image_tag "twitter.png", alt: "Twitter"

        li
          = link_to "https://gitlab.com/deivid-rodriguez/nipanipa" do
            = image_tag "gitlab.png", alt: "GitLab"

        li
          = link_to "http://www.pinterest.com/trasteverestu/nipa-nipa" do
            = image_tag "pinterest.png", alt: "pinterest"

        li
          = link_to "http://vimeo.com/nipanipa" do
            = image_tag "vimeo.png", alt: "vimeo"

app/views/layouts/_head.html.slim
- title = full_title(yield(:title))

head
  meta content="width=device-width, initial-scale=1" name="viewport"

  title= title

  - content = content_for?(:description) ? yield(:description) : title
  meta content=content name="description"

  - localeless_url = url_for(locale: nil, only_path: false)
  link rel="alternate" href=localeless_url hreflang="x-default"

  - I18n.available_locales.each do |locale|
    - locale_url = url_for(locale: locale, only_path: false)
    link rel="alternate" href=locale_url hreflang=locale

  = favicon_link_tag

  = stylesheet_link_tag "application", media: "all"
  = javascript_include_tag "application"

  = csrf_meta_tags

  = render "layouts/analytics" if Rails.env.production?

app/views/layouts/_header.html.slim
nav.navbar.navbar-default role="navigation"
  .navbar-header
    = link_to root_path, class: "navbar-brand" do
      = image_tag logo_pic, alt: "NiPaNiPa"

    button.navbar-toggle.collapsed data={ toggle: "collapse",
                                          target: ".navbar-collapse" }
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar

  .navbar-collapse.collapse.navbar-right
    ul.nav.navbar-nav.pull-right
      li= link_to t(".donate"), new_donation_path
      li= link_to t(".search"), users_path
      li= link_to t("static_pages.help.title"), help_path

      - if user_signed_in?
        li= link_to t("users.show.profile"), current_user
      - elsif !signup_page?(request.path)
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#" role="button"
            = t(".signup")
            b.caret
          ul.dropdown-menu.with-small-arrow
            li= link_to t("activerecord.models.host"), host_registration_path
            li= link_to t("activerecord.models.volunteer"),
                  volunteer_registration_path
      - if user_signed_in?
        li= link_to t("sessions.signout"),
                    destroy_user_session_path,
                    method: :delete
      - elsif !request.path.match?(/signin/)
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#" role="button"
            = t("sessions.signin")
            strong.caret
          .dropdown-menu.with-small-arrow
            .signin-dropdown= render "shared/signin"
      li.dropdown
        a.dropdown-toggle data-toggle="dropdown" href="#" role="button"
          = t(".language")
          b.caret
        ul.dropdown-menu.with-small-arrow
          - Language.where(code: I18n.available_locales).find_each do |lang|
            li= link_to_unless_current lang, locale: lang.code

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  / https://github.com/plataformatec/devise/pull/1993/commits
  - next unless msg.is_a?(String)

  = content_tag :div, class: "alert #{bootstrap_class_for(name)}" do
    = msg

app/views/layouts/application.html.slim
doctype html

html
  = render "layouts/head"

  body
    div class=(params[:action] == "home" ? "home" : "inner")
      .wrapper
        = render "layouts/header"
        = render "layouts/messages"

      main role="main"
        = yield

    = render "layouts/footer"